---
name: "Tronbyt Server"
version: "0.1.9"
slug: "tronbyt_server"
description: "Manage your apps on your Tronbyt (flashed Tidbyt) completely locally without relying on Tidbyt's backend servers."
arch:
  - aarch64
  - amd64
url: "https://github.com/kaffolder7/ha-app-tronbyt-server"
startup: application
webui: "http://[HOST]:[PORT:8000]"
boot: auto
ports:
  8000/tcp: null
ports_description:
  8000/tcp: "Tronbyt Server Web UI"
apparmor: true
options:
  production: true
  enable_user_registration: false
  single_user_auto_login: false
  github_token: ""
  system_apps_repo: ""
schema:
  production: bool
  enable_user_registration: bool
  single_user_auto_login: bool
  github_token: "password?"
  system_apps_repo: "str?"
image: "ghcr.io/kaffolder7/{arch}-app-tronbyt-server"
panel_icon: "mdi:server-network"

# Let Docker init handle zombie reaping (Tronbytâ€™s own compose uses init: true)
init: true
